### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by FerLuisxd** [misyaguziya/VRCT#2]
Hello! This is a really cool project! I have so questions and suggestions
Have you looked into open ai's whisper model? I can run locally and transcribe (and translate) voice! But the benefit is that is free! (and probably faster).
Also another option for translating text could be using the google actions api (which is free up to 5000 times a day).

**Comment by misyaguziya** [comment]
Hello.
Yes, I know about whisper.
I actually implemented it in VRCT and tried it, but the Japanese transcription accuracy is poor and very slow since the processing is done by CPU...
(I think you can try by changing `recognize_google` to `recognize_whisper` in `audio_transcriber.py`)
GPU is required if you want to do real-time transcription, but I am holding off because it seems difficult to include libraries such as cuda, etc.

Are the translation options [DeepL, Google, Bing] not enough?

Thanks!

**Comment by misyaguziya** [comment]
I closed it by mistake...

**Comment by FerLuisxd** [comment]
Hello! Thanks for the response
Currently it uses DeepL for Speech to text + translation, right?
I'm wondering if we could use something like what this app uses http://www.sayonari.com/trans_asr/asr.html
I believe it uses the [SpeechRecognition API ](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) for speech to text and https://script.google.com/home for translating the text to the desired language.

I may have it wrong but what are the limitions for DeepL (is it free?)

**Comment by misyaguziya** [comment]
I feel that there is a discrepancy in recognition.
DeepL only uses translation functionality.
We use the Google Speech Recognition API for transcription.
You can use DeepL for translation, but you can also choose google or bing. This translation is accessed from the web, so there are no restrictions.
