### ISSUE TITLE
I can`t open it

### ISSUE THREAD

**Issue by parseva1** [misyaguziya/VRCT#6]
I try to use VPN in Japen and America to download and install. 
stop in starting up then the window just Disappeared. 
I don`t know why and what happend.
And may first time download the translate fail.

I use python in Python 3.11.5. and VRcaht open the option.
In windows 11.

**Comment by misyaguziya** [comment]
Dear parseva1,

I understand that you are experiencing issues with running the application. To better assist you, could you provide some additional details?

1. Could you please clarify the operating environment in which you are running the application? Specifically, let us know if you are executing it using python main.py or if you are using an executable (exe) file.

2. In case the application fails to launch, could you share the stack trace of the error or check if there's an error.log file generated in the directory where you are running the application? This information will be helpful for diagnosing the issue.

Your cooperation in providing these details will aid us in offering a more accurate solution to the problem.

Thank you.

**Comment by misyaguziya** [comment]
It seems like we haven't received any response from you regarding this issue for quite some time. In order to keep our issue tracker organized, we'll be closing this issue for now. 

If you still encounter this problem or have further questions, please feel free to reopen this issue or create a new one. We're here to help!

Best regards,
